spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ordersystem}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # in prod consider: validate or managed migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false        # set to true only when debugging

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.upskilldev.ordersystem: DEBUG
    org.springframework.web: INFO

security:
  jwt:
    secret: ${JWT_SECRET:ChangeMePlease}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

product:
  image:
    upload-dir: uploads/images